algoritmo "Primeiro"
//==================================================================
//1) Escreva um programa que mostre na tela a mensagem "Olá, Mundo!"
//==================================================================
var
    msg: caractere
inicio
      msg <- "Olá, Mundo!"
      escreval("msg")
      escreval(msg)
      escreval("mensagem ", msg)
      escreval("! + Ctrl+espaço para aparecer a estrutura")

fimalgoritmo


